# Generated by Django 5.1.3 on 2025-05-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidaconsumida',
            name='comida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kal_app.comida'),
        ),
    ]
