# Generated by Django 5.1.3 on 2025-06-11 13:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kal_app', '0002_alter_pesoregistrado_foto_pesaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_Perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_Perfil'),
        ),
    ]
