# Generated by Django 5.1.3 on 2025-06-11 15:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kal_app', '0003_alter_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesoregistrado',
            name='foto_pesaje',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_pesaje'),
        ),
    ]
