# Generated by Django 5.1.3 on 2025-06-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kal_app', '0004_alter_pesoregistrado_foto_pesaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='kal_app.usuario'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='kal_app.usuario'),
        ),
        migrations.AlterField(
            model_name='pesoregistrado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='kal_app.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_perms_set', to='auth.permission'),
        ),
    ]
